/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author Aluno
 */
public class AvaliarJogo extends javax.swing.JFrame {

    /**
     * Creates new form AvaliarJogo
     */
    public AvaliarJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupEnredo = new javax.swing.ButtonGroup();
        groupGraficos = new javax.swing.ButtonGroup();
        groupJogabilidade = new javax.swing.ButtonGroup();
        groupAudio = new javax.swing.ButtonGroup();
        radioBomEnredo = new javax.swing.JRadioButton();
        buttonCadastrarAvaliacao = new javax.swing.JButton();
        textNomeUsuario = new javax.swing.JTextField();
        radioExcelenteEnredo = new javax.swing.JRadioButton();
        labelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNomeJogo = new javax.swing.JTextField();
        radioRuimEnredo = new javax.swing.JRadioButton();
        radioPessimoEnredo = new javax.swing.JRadioButton();
        radioRegularEnredo = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        radioBomGraficos = new javax.swing.JRadioButton();
        radioRuimGraficos = new javax.swing.JRadioButton();
        radioPessimoGraficos = new javax.swing.JRadioButton();
        radioRegularGraficos = new javax.swing.JRadioButton();
        radioExcelenteGraficos = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        radioBomJogabilidade = new javax.swing.JRadioButton();
        radioRuimJogabilidade = new javax.swing.JRadioButton();
        radioPessimoJogabilidade = new javax.swing.JRadioButton();
        radioRegularJogabilidade = new javax.swing.JRadioButton();
        radioExcelenteJogabilidade = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        radioPomAudio = new javax.swing.JRadioButton();
        radioRuimAudio = new javax.swing.JRadioButton();
        radioPessimoAudio = new javax.swing.JRadioButton();
        radioRegularAudio = new javax.swing.JRadioButton();
        radioExcelenteAudio = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textComentarios = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        groupEnredo.add(radioBomEnredo);
        radioBomEnredo.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioBomEnredo.setText("Bom");
        radioBomEnredo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBomEnredoActionPerformed(evt);
            }
        });

        buttonCadastrarAvaliacao.setFont(new java.awt.Font("Game Over", 0, 64)); // NOI18N
        buttonCadastrarAvaliacao.setText("Cadastrar");
        buttonCadastrarAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarAvaliacaoActionPerformed(evt);
            }
        });

        textNomeUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        groupEnredo.add(radioExcelenteEnredo);
        radioExcelenteEnredo.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioExcelenteEnredo.setText("Excelente");
        radioExcelenteEnredo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExcelenteEnredoActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Game Over", 0, 128)); // NOI18N
        labelTitulo.setText("Cadastrar Avaliacao");

        jLabel1.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel1.setText("Nome do Usuario:");

        jLabel3.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel3.setText("Comentarios:");

        textNomeJogo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        groupEnredo.add(radioRuimEnredo);
        radioRuimEnredo.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioRuimEnredo.setText("Ruim");
        radioRuimEnredo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRuimEnredoActionPerformed(evt);
            }
        });

        groupEnredo.add(radioPessimoEnredo);
        radioPessimoEnredo.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioPessimoEnredo.setText("Pessimo");
        radioPessimoEnredo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPessimoEnredoActionPerformed(evt);
            }
        });

        groupEnredo.add(radioRegularEnredo);
        radioRegularEnredo.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioRegularEnredo.setText("Regular");
        radioRegularEnredo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRegularEnredoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel8.setText("Enredo:");

        groupGraficos.add(radioBomGraficos);
        radioBomGraficos.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioBomGraficos.setText("Bom");
        radioBomGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBomGraficosActionPerformed(evt);
            }
        });

        groupGraficos.add(radioRuimGraficos);
        radioRuimGraficos.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioRuimGraficos.setText("Ruim");
        radioRuimGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRuimGraficosActionPerformed(evt);
            }
        });

        groupGraficos.add(radioPessimoGraficos);
        radioPessimoGraficos.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioPessimoGraficos.setText("Pessimo");
        radioPessimoGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPessimoGraficosActionPerformed(evt);
            }
        });

        groupGraficos.add(radioRegularGraficos);
        radioRegularGraficos.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioRegularGraficos.setText("Regular");
        radioRegularGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRegularGraficosActionPerformed(evt);
            }
        });

        groupGraficos.add(radioExcelenteGraficos);
        radioExcelenteGraficos.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioExcelenteGraficos.setText("Excelente");
        radioExcelenteGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExcelenteGraficosActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel9.setText("Graficos:");

        groupJogabilidade.add(radioBomJogabilidade);
        radioBomJogabilidade.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioBomJogabilidade.setText("Bom");
        radioBomJogabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBomJogabilidadeActionPerformed(evt);
            }
        });

        groupJogabilidade.add(radioRuimJogabilidade);
        radioRuimJogabilidade.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioRuimJogabilidade.setText("Ruim");
        radioRuimJogabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRuimJogabilidadeActionPerformed(evt);
            }
        });

        groupJogabilidade.add(radioPessimoJogabilidade);
        radioPessimoJogabilidade.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioPessimoJogabilidade.setText("Pessimo");
        radioPessimoJogabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPessimoJogabilidadeActionPerformed(evt);
            }
        });

        groupJogabilidade.add(radioRegularJogabilidade);
        radioRegularJogabilidade.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioRegularJogabilidade.setText("Regular");
        radioRegularJogabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRegularJogabilidadeActionPerformed(evt);
            }
        });

        groupJogabilidade.add(radioExcelenteJogabilidade);
        radioExcelenteJogabilidade.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioExcelenteJogabilidade.setText("Excelente");
        radioExcelenteJogabilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExcelenteJogabilidadeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel10.setText("Jogabilidade: ");

        jLabel11.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel11.setText("Audio:");

        groupAudio.add(radioPomAudio);
        radioPomAudio.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioPomAudio.setText("Bom");
        radioPomAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPomAudioActionPerformed(evt);
            }
        });

        groupAudio.add(radioRuimAudio);
        radioRuimAudio.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioRuimAudio.setText("Ruim");
        radioRuimAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRuimAudioActionPerformed(evt);
            }
        });

        groupAudio.add(radioPessimoAudio);
        radioPessimoAudio.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioPessimoAudio.setText("Pessimo");
        radioPessimoAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPessimoAudioActionPerformed(evt);
            }
        });

        groupAudio.add(radioRegularAudio);
        radioRegularAudio.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioRegularAudio.setText("Regular");
        radioRegularAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRegularAudioActionPerformed(evt);
            }
        });

        groupAudio.add(radioExcelenteAudio);
        radioExcelenteAudio.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioExcelenteAudio.setText("Excelente");
        radioExcelenteAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExcelenteAudioActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel4.setText("Nome do Jogo: ");

        textComentarios.setColumns(20);
        textComentarios.setRows(5);
        jScrollPane1.setViewportView(textComentarios);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(radioPessimoGraficos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(radioRuimGraficos)
                                    .addGap(14, 14, 14)
                                    .addComponent(radioRegularGraficos)
                                    .addGap(18, 18, 18)
                                    .addComponent(radioBomGraficos)
                                    .addGap(12, 12, 12)
                                    .addComponent(radioExcelenteGraficos))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(radioPessimoEnredo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(radioRuimEnredo)
                                    .addGap(14, 14, 14)
                                    .addComponent(radioRegularEnredo)
                                    .addGap(18, 18, 18)
                                    .addComponent(radioBomEnredo)
                                    .addGap(12, 12, 12)
                                    .addComponent(radioExcelenteEnredo))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(radioPessimoAudio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(radioRuimAudio)
                                    .addGap(14, 14, 14)
                                    .addComponent(radioRegularAudio)
                                    .addGap(18, 18, 18)
                                    .addComponent(radioPomAudio)
                                    .addGap(12, 12, 12)
                                    .addComponent(radioExcelenteAudio))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(radioPessimoJogabilidade)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(radioRuimJogabilidade)
                                    .addGap(14, 14, 14)
                                    .addComponent(radioRegularJogabilidade)
                                    .addGap(18, 18, 18)
                                    .addComponent(radioBomJogabilidade)
                                    .addGap(12, 12, 12)
                                    .addComponent(radioExcelenteJogabilidade)))
                            .addGap(1, 1, 1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(387, 387, 387)
                        .addComponent(buttonCadastrarAvaliacao)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labelTitulo)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPessimoEnredo)
                    .addComponent(radioRegularEnredo)
                    .addComponent(radioRuimEnredo)
                    .addComponent(radioBomEnredo)
                    .addComponent(radioExcelenteEnredo)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPessimoGraficos)
                    .addComponent(radioRegularGraficos)
                    .addComponent(radioRuimGraficos)
                    .addComponent(radioBomGraficos)
                    .addComponent(radioExcelenteGraficos)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPessimoJogabilidade)
                    .addComponent(radioRegularJogabilidade)
                    .addComponent(radioRuimJogabilidade)
                    .addComponent(radioBomJogabilidade)
                    .addComponent(radioExcelenteJogabilidade)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPessimoAudio)
                    .addComponent(radioRegularAudio)
                    .addComponent(radioRuimAudio)
                    .addComponent(radioPomAudio)
                    .addComponent(radioExcelenteAudio)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(buttonCadastrarAvaliacao)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radioBomEnredoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBomEnredoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBomEnredoActionPerformed

    private void buttonCadastrarAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarAvaliacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastrarAvaliacaoActionPerformed

    private void radioExcelenteEnredoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExcelenteEnredoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioExcelenteEnredoActionPerformed

    private void radioRuimEnredoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRuimEnredoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRuimEnredoActionPerformed

    private void radioPessimoEnredoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPessimoEnredoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPessimoEnredoActionPerformed

    private void radioRegularEnredoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRegularEnredoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRegularEnredoActionPerformed

    private void radioBomGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBomGraficosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBomGraficosActionPerformed

    private void radioRuimGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRuimGraficosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRuimGraficosActionPerformed

    private void radioPessimoGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPessimoGraficosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPessimoGraficosActionPerformed

    private void radioRegularGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRegularGraficosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRegularGraficosActionPerformed

    private void radioExcelenteGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExcelenteGraficosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioExcelenteGraficosActionPerformed

    private void radioBomJogabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBomJogabilidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBomJogabilidadeActionPerformed

    private void radioRuimJogabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRuimJogabilidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRuimJogabilidadeActionPerformed

    private void radioPessimoJogabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPessimoJogabilidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPessimoJogabilidadeActionPerformed

    private void radioRegularJogabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRegularJogabilidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRegularJogabilidadeActionPerformed

    private void radioExcelenteJogabilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExcelenteJogabilidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioExcelenteJogabilidadeActionPerformed

    private void radioPomAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPomAudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPomAudioActionPerformed

    private void radioRuimAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRuimAudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRuimAudioActionPerformed

    private void radioPessimoAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPessimoAudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPessimoAudioActionPerformed

    private void radioRegularAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRegularAudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRegularAudioActionPerformed

    private void radioExcelenteAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExcelenteAudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioExcelenteAudioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvaliarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvaliarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvaliarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvaliarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvaliarJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrarAvaliacao;
    private javax.swing.ButtonGroup groupAudio;
    private javax.swing.ButtonGroup groupEnredo;
    private javax.swing.ButtonGroup groupGraficos;
    private javax.swing.ButtonGroup groupJogabilidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JRadioButton radioBomEnredo;
    private javax.swing.JRadioButton radioBomGraficos;
    private javax.swing.JRadioButton radioBomJogabilidade;
    private javax.swing.JRadioButton radioExcelenteAudio;
    private javax.swing.JRadioButton radioExcelenteEnredo;
    private javax.swing.JRadioButton radioExcelenteGraficos;
    private javax.swing.JRadioButton radioExcelenteJogabilidade;
    private javax.swing.JRadioButton radioPessimoAudio;
    private javax.swing.JRadioButton radioPessimoEnredo;
    private javax.swing.JRadioButton radioPessimoGraficos;
    private javax.swing.JRadioButton radioPessimoJogabilidade;
    private javax.swing.JRadioButton radioPomAudio;
    private javax.swing.JRadioButton radioRegularAudio;
    private javax.swing.JRadioButton radioRegularEnredo;
    private javax.swing.JRadioButton radioRegularGraficos;
    private javax.swing.JRadioButton radioRegularJogabilidade;
    private javax.swing.JRadioButton radioRuimAudio;
    private javax.swing.JRadioButton radioRuimEnredo;
    private javax.swing.JRadioButton radioRuimGraficos;
    private javax.swing.JRadioButton radioRuimJogabilidade;
    private javax.swing.JTextArea textComentarios;
    private javax.swing.JTextField textNomeJogo;
    private javax.swing.JTextField textNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
