/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import controle.ArquivoTexto;
import java.io.IOException;
/**
 *
 * @author samue
 */
public class CadastrarUsuario extends javax.swing.JFrame {
    
    ArquivoTexto usuTxt = new ArquivoTexto();
    
    /**
     * Creates new form CadastroUsuario
     */
    public CadastrarUsuario() {
        initComponents();
        setResizable(false);
        try{
            usuTxt.criaArquivo();
        } catch (IOException e){
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGenero = new javax.swing.ButtonGroup();
        labelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textSobrenome = new javax.swing.JTextField();
        textSenha = new javax.swing.JPasswordField();
        textCSenha = new javax.swing.JPasswordField();
        radioFps = new javax.swing.JRadioButton();
        radioEstrategia = new javax.swing.JRadioButton();
        radioRpg = new javax.swing.JRadioButton();
        radioTerror = new javax.swing.JRadioButton();
        radioCorrida = new javax.swing.JRadioButton();
        radioCasual = new javax.swing.JRadioButton();
        textJogoFavorito = new javax.swing.JTextField();
        buttonCadastrarUsuario = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelTitulo.setFont(new java.awt.Font("Game Over", 0, 128)); // NOI18N
        labelTitulo.setText("Cadastrar Usuário");

        jLabel1.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel3.setText("Sobrenome:");

        jLabel4.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel5.setText("Senha:");

        jLabel6.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel6.setText("Confirme a senha:");

        jLabel7.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel7.setText("Jogo Favorito:");

        jLabel8.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel8.setText("Genero Favorito:");

        textNome.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        textEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        textSobrenome.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        textSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenhaActionPerformed(evt);
            }
        });

        textCSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCSenhaActionPerformed(evt);
            }
        });

        groupGenero.add(radioFps);
        radioFps.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioFps.setText("FPS");
        radioFps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFpsActionPerformed(evt);
            }
        });

        groupGenero.add(radioEstrategia);
        radioEstrategia.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioEstrategia.setText("Estrategia");
        radioEstrategia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEstrategiaActionPerformed(evt);
            }
        });

        groupGenero.add(radioRpg);
        radioRpg.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioRpg.setText("RPG");
        radioRpg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRpgActionPerformed(evt);
            }
        });

        groupGenero.add(radioTerror);
        radioTerror.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioTerror.setText("Terror");
        radioTerror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTerrorActionPerformed(evt);
            }
        });

        groupGenero.add(radioCorrida);
        radioCorrida.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioCorrida.setText("Corrida");
        radioCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCorridaActionPerformed(evt);
            }
        });

        groupGenero.add(radioCasual);
        radioCasual.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioCasual.setText("Casual");
        radioCasual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCasualActionPerformed(evt);
            }
        });

        textJogoFavorito.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        buttonCadastrarUsuario.setFont(new java.awt.Font("Game Over", 0, 64)); // NOI18N
        buttonCadastrarUsuario.setText("Cadastrar");
        buttonCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarUsuarioActionPerformed(evt);
            }
        });

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gerenciar Usuario");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(textCSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(120, 120, 120)
                                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(radioFps)
                                            .addGap(18, 18, 18)
                                            .addComponent(radioEstrategia)
                                            .addGap(18, 18, 18)
                                            .addComponent(radioRpg)
                                            .addGap(18, 18, 18)
                                            .addComponent(radioTerror)
                                            .addGap(18, 18, 18)
                                            .addComponent(radioCorrida)))
                                    .addGap(18, 18, 18)
                                    .addComponent(radioCasual)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textJogoFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(buttonCadastrarUsuario)))))
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labelTitulo)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(textSenha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioFps)
                    .addComponent(radioEstrategia)
                    .addComponent(radioRpg)
                    .addComponent(radioTerror)
                    .addComponent(radioCorrida)
                    .addComponent(radioCasual))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textJogoFavorito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonCadastrarUsuario))
                .addGap(56, 56, 56))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textCSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCSenhaActionPerformed

    private void textSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSenhaActionPerformed

    private void radioFpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioFpsActionPerformed

    private void radioEstrategiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEstrategiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEstrategiaActionPerformed

    private void radioRpgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRpgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRpgActionPerformed

    private void radioTerrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTerrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTerrorActionPerformed

    private void radioCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCorridaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCorridaActionPerformed

    private void radioCasualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCasualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCasualActionPerformed

    private void buttonCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastrarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrarUsuario;
    private javax.swing.ButtonGroup groupGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JRadioButton radioCasual;
    private javax.swing.JRadioButton radioCorrida;
    private javax.swing.JRadioButton radioEstrategia;
    private javax.swing.JRadioButton radioFps;
    private javax.swing.JRadioButton radioRpg;
    private javax.swing.JRadioButton radioTerror;
    private javax.swing.JPasswordField textCSenha;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textJogoFavorito;
    private javax.swing.JTextField textNome;
    private javax.swing.JPasswordField textSenha;
    private javax.swing.JTextField textSobrenome;
    // End of variables declaration//GEN-END:variables
}
