/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author Aluno
 */
public class CadastrarJogo extends javax.swing.JFrame {
    
    /**
     * Creates new form CadastrarJogo
     */
    public CadastrarJogo() {
        initComponents();
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupGenero = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        radioTerror = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        radioCorrida = new javax.swing.JRadioButton();
        radioCasual = new javax.swing.JRadioButton();
        radioFps = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        buttonCadastrarJogo = new javax.swing.JButton();
        textNomeJogo = new javax.swing.JTextField();
        labelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        texLancamento = new javax.swing.JTextField();
        textProdutora = new javax.swing.JTextField();
        radioEstrategia = new javax.swing.JRadioButton();
        radioRpg = new javax.swing.JRadioButton();
        textPublisher = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel4.setText("Publisher: ");

        groupGenero.add(radioTerror);
        radioTerror.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioTerror.setText("Terror");
        radioTerror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTerrorActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel5.setText("Data de Lancamento: ");

        groupGenero.add(radioCorrida);
        radioCorrida.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioCorrida.setText("Corrida");
        radioCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCorridaActionPerformed(evt);
            }
        });

        groupGenero.add(radioCasual);
        radioCasual.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioCasual.setText("Casual");
        radioCasual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCasualActionPerformed(evt);
            }
        });

        groupGenero.add(radioFps);
        radioFps.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioFps.setText("FPS");
        radioFps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFpsActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel8.setText("Genero do Jogo:");

        buttonCadastrarJogo.setFont(new java.awt.Font("Game Over", 0, 64)); // NOI18N
        buttonCadastrarJogo.setText("Cadastrar");
        buttonCadastrarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarJogoActionPerformed(evt);
            }
        });

        textNomeJogo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        labelTitulo.setFont(new java.awt.Font("Game Over", 0, 128)); // NOI18N
        labelTitulo.setText("Cadastrar Jogo");

        jLabel1.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("pixeljosh6", 0, 14)); // NOI18N
        jLabel3.setText("Produtora: ");

        texLancamento.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        textProdutora.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        groupGenero.add(radioEstrategia);
        radioEstrategia.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioEstrategia.setText("Estrategia");
        radioEstrategia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEstrategiaActionPerformed(evt);
            }
        });

        groupGenero.add(radioRpg);
        radioRpg.setFont(new java.awt.Font("pixeljosh6", 0, 12)); // NOI18N
        radioRpg.setText("RPG");
        radioRpg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRpgActionPerformed(evt);
            }
        });

        textPublisher.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textProdutora, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(texLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(radioFps)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioEstrategia)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttonCadastrarJogo)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(radioRpg)
                                                .addGap(18, 18, 18)
                                                .addComponent(radioTerror)
                                                .addGap(18, 18, 18)
                                                .addComponent(radioCorrida)))))
                                .addGap(18, 18, 18)
                                .addComponent(radioCasual))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(labelTitulo)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelTitulo)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textProdutora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioFps)
                    .addComponent(radioEstrategia)
                    .addComponent(radioRpg)
                    .addComponent(radioTerror)
                    .addComponent(radioCorrida)
                    .addComponent(radioCasual))
                .addGap(36, 36, 36)
                .addComponent(buttonCadastrarJogo)
                .addGap(75, 75, 75))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radioTerrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTerrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioTerrorActionPerformed

    private void radioCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCorridaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCorridaActionPerformed

    private void radioCasualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCasualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCasualActionPerformed

    private void radioFpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioFpsActionPerformed

    private void buttonCadastrarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastrarJogoActionPerformed

    private void radioEstrategiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEstrategiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEstrategiaActionPerformed

    private void radioRpgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRpgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRpgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrarJogo;
    private javax.swing.ButtonGroup groupGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JRadioButton radioCasual;
    private javax.swing.JRadioButton radioCorrida;
    private javax.swing.JRadioButton radioEstrategia;
    private javax.swing.JRadioButton radioFps;
    private javax.swing.JRadioButton radioRpg;
    private javax.swing.JRadioButton radioTerror;
    private javax.swing.JTextField texLancamento;
    private javax.swing.JTextField textNomeJogo;
    private javax.swing.JTextField textProdutora;
    private javax.swing.JTextField textPublisher;
    // End of variables declaration//GEN-END:variables
}
